=== sadie27/TrabajoDistribuidos2025/bin/xml/DTD/PalabReto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dia (letraCentral, letra+, palabra+)>
<!ATTLIST dia
    id CDATA #REQUIRED
>
<!ELEMENT letraCentral (#PCDATA)>
<!ELEMENT letra (#PCDATA)>
<!ELEMENT palabra (contenido, palabreto?)>
<!ATTLIST palabra
    long CDATA #REQUIRED
>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT palabreto EMPTY>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia22.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="22">
  <letraCentral>i</letraCentral>
  <letra>d</letra>
  <letra>e</letra>
  <letra>s</letra>
  <letra>c</letra>
  <letra>n</letra>
  <letra>i</letra>
  <letra>r</letra>
  
  <palabra long="3">
    <contenido>cid</contenido>
  </palabra>
  <palabra long="3">
    <contenido>din</contenido>
  </palabra>
  <palabra long="3">
    <contenido>DNI</contenido>
  </palabra>
  <palabra long="3">
    <contenido>nin</contenido>
  </palabra>
  <palabra long="3">
    <contenido>Rin</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ris</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sic</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sin</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ceni</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cien</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cinc</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cine</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cric</contenido>
  </palabra>
  <palabra long="4">
    <contenido>crin</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dire</contenido>
  </palabra>
  <palabra long="4">
    <contenido>inri</contenido>
  </palabra>
  <palabra long="4">
    <contenido>iris</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ISSN</contenido>
  </palabra>
  <palabra long="4">
    <contenido>neis</contenido>
  </palabra>
  <palabra long="4">
    <contenido>RDSI</contenido>
  </palabra>
  <palabra long="4">
    <contenido>reir</contenido>
  </palabra>
  <palabra long="4">
    <contenido>reis</contenido>
  </palabra>
  <palabra long="4">
    <contenido>seis</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sesi</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sien</contenido>
  </palabra>
  <palabra long="5">
    <contenido>circe</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cisne</contenido>
  </palabra>
  <palabra long="5">
    <contenido>decir</contenido>
  </palabra>
  <palabra long="5">
    <contenido>diesi</contenido>
  </palabra>
  <palabra long="5">
    <contenido>indie</contenido>
  </palabra>
  <palabra long="5">
    <contenido>iride</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rinde</contenido>
  </palabra>
  <palabra long="5">
    <contenido>seise</contenido>
  </palabra>
  <palabra long="5">
    <contenido>serie</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sirin</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cernir</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cierne</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cierre</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cricri</contenido>
  </palabra>
  <palabra long="6">
    <contenido>crisis</contenido>
  </palabra>
  <palabra long="6">
    <contenido>diesis</contenido>
  </palabra>
  <palabra long="6">
    <contenido>edrisi</contenido>
  </palabra>
  <palabra long="6">
    <contenido>indice</contenido>
  </palabra>
  <palabra long="6">
    <contenido>recien</contenido>
  </palabra>
  <palabra long="6">
    <contenido>rendir</contenido>
  </palabra>
  <palabra long="6">
    <contenido>seisen</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sereni</contenido>
  </palabra>
  <palabra long="6">
    <contenido>serrin</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sienes</contenido>
  </palabra>
  <palabra long="6">
    <contenido>siriri</contenido>
  </palabra>
  <palabra long="7">
    <contenido>cedride</contenido>
  </palabra>
  <palabra long="7">
    <contenido>decidir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>diceres</contenido>
  </palabra>
  <palabra long="7">
    <contenido>disidir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ecdisis</contenido>
  </palabra>
  <palabra long="7">
    <contenido>enserir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>incidir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>inserir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>iriense</contenido>
  </palabra>
  <palabra long="7">
    <contenido>redecir</contenido>
  </palabra>
  <palabra long="7">
    <contenido>residir</contenido>
  </palabra>
  <palabra long="8">
    <contenido>circense</contenido>
  </palabra>
  <palabra long="8">
    <contenido>decernir</contenido>
  </palabra>
  <palabra long="8">
    <contenido>desdecir</contenido>
  </palabra>
  <palabra long="8">
    <contenido>dieresis</contenido>
  </palabra>
  <palabra long="8">
    <contenido>encierre</contenido>
  </palabra>
  <palabra long="8">
    <contenido>escindir</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>cenicense</contenido>
  </palabra>
  <palabra long="9">
    <contenido>descendir</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>dieciseis</contenido>
  </palabra>
  <palabra long="9">
    <contenido>discerner</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>discernir</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>reincidir</contenido>
  </palabra>
  <palabra long="9">
    <contenido>rescindir</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>sineresis</contenido>
  </palabra>
  <palabra long="10">
    <contenido>sinderesis</contenido>
  </palabra>
  <palabra long="11">
    <contenido>cenicerense</contenido>
  </palabra>
  <palabra long="11">
    <contenido>cisneriense</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="3">
  <letraCentral>m</letraCentral>
  <letra>v</letra>
  <letra>e</letra>
  <letra>l</letra>
  <letra>o</letra>
  <letra>d</letra>
  <letra>r</letra>
  
  <palabra long="4">
    <contenido>demo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>demode</contenido>
  </palabra>
  <palabra long="9">
    <contenido>demoledor</contenido>
  </palabra>
  <palabra long="7">
    <contenido>demoler</contenido>
  </palabra>
  <palabra long="3">
    <contenido>dom</contenido>
  </palabra>
  <palabra long="4">
    <contenido>domo</contenido>
  </palabra>
  <palabra long="3">
    <contenido>eme</contenido>
  </palabra>
  <palabra long="4">
    <contenido>leme</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lomo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>medo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>medro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>mele</contenido>
  </palabra>
  <palabra long="6">
    <contenido>melero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>meme</contenido>
  </palabra>
  <palabra long="4">
    <contenido>memo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>meollo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>mere</contenido>
  </palabra>
  <palabra long="5">
    <contenido>merlo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>mero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>merode</contenido>
  </palabra>
  <palabra long="7">
    <contenido>merodeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>merol</contenido>
  </palabra>
  <palabra long="3">
    <contenido>mod</contenido>
  </palabra>
  <palabra long="6">
    <contenido>modelo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>modem</contenido>
  </palabra>
  <palabra long="4">
    <contenido>modo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>modorro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>moer</contenido>
  </palabra>
  <palabra long="3">
    <contenido>mol</contenido>
  </palabra>
  <palabra long="5">
    <contenido>molde</contenido>
  </palabra>
  <palabra long="6">
    <contenido>moldeo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>moldero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>mole</contenido>
  </palabra>
  <palabra long="8">
    <contenido>moledero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>moledor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>moler</contenido>
  </palabra>
  <palabra long="6">
    <contenido>molero</contenido>
  </palabra>
  <palabra long="5">
    <contenido>molle</contenido>
  </palabra>
  <palabra long="7">
    <contenido>molledo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>mollero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>molo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>momero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>momo</contenido>
  </palabra>
  <palabra long="3">
    <contenido>mor</contenido>
  </palabra>
  <palabra long="8">
    <contenido>mordedor</contenido>
  </palabra>
  <palabra long="6">
    <contenido>morder</contenido>
  </palabra>
  <palabra long="5">
    <contenido>moreo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>moro</contenido>
  </palabra>
  <palabra long="6">
    <contenido>morreo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>morro</contenido>
  </palabra>
  <palabra long="7">
    <contenido>movedor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>mover</contenido>
  </palabra>
  <palabra long="6">
    <contenido>olmedo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>olmo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>omero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>remedo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>remero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>remo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>remoler</contenido>
  </palabra>
  <palabra long="9">
    <contenido>remollero</contenido>
  </palabra>
  <palabra long="10">
    <contenido>remordedor</contenido>
  </palabra>
  <palabra long="8">
    <contenido>remorder</contenido>
  </palabra>
  <palabra long="9">
    <contenido>removedor</contenido>
  </palabra>
  <palabra long="7">
    <contenido>remover</contenido>
  </palabra>
  <palabra long="5">
    <contenido>romeo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>romero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>romo</contenido>
  </palabra>
  <palabra long="9">
    <contenido>velodromo</contenido>
    <palabreto/>
  </palabra>
  <palabra long="5">
    <contenido>verme</contenido>
  </palabra>
  <palabra long="5">
    <contenido>vomer</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="16">
  <letraCentral>s</letraCentral>
  <letra>y</letra>
  <letra>a</letra>
  <letra>n</letra>
  <letra>g</letra>
  <letra>u</letra>
  <letra>e</letra>
  <letra>s</letra>
  
  <palabra long="3">
    <contenido>asa</contenido>
  </palabra>
  <palabra long="3">
    <contenido>esa</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ese</contenido>
  </palabra>
  <palabra long="3">
    <contenido>gas</contenido>
  </palabra>
  <palabra long="3">
    <contenido>san</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sen</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ses</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sus</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ansa</contenido>
  </palabra>
  <palabra long="4">
    <contenido>asna</contenido>
  </palabra>
  <palabra long="4">
    <contenido>esas</contenido>
  </palabra>
  <palabra long="4">
    <contenido>gasa</contenido>
  </palabra>
  <palabra long="4">
    <contenido>gusa</contenido>
  </palabra>
  <palabra long="4">
    <contenido>nasa</contenido>
  </palabra>
  <palabra long="4">
    <contenido>saga</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sagu</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sana</contenido>
  </palabra>
  <palabra long="4">
    <contenido>saya</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sega</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sena</contenido>
  </palabra>
  <palabra long="4">
    <contenido>suya</contenido>
  </palabra>
  <palabra long="5">
    <contenido>agnus</contenido>
  </palabra>
  <palabra long="5">
    <contenido>asana</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ensay</contenido>
  </palabra>
  <palabra long="5">
    <contenido>gansa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>gauss</contenido>
  </palabra>
  <palabra long="5">
    <contenido>guasa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nansa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nansu</contenido>
  </palabra>
  <palabra long="5">
    <contenido>negus</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nesga</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nuesa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sansa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sauna</contenido>
  </palabra>
  <palabra long="5">
    <contenido>segun</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sesen</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sesga</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sunna</contenido>
  </palabra>
  <palabra long="6">
    <contenido>ananas</contenido>
  </palabra>
  <palabra long="6">
    <contenido>asnuna</contenido>
  </palabra>
  <palabra long="6">
    <contenido>ensaye</contenido>
  </palabra>
  <palabra long="6">
    <contenido>guayas</contenido>
  </palabra>
  <palabra long="6">
    <contenido>nausea</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sanana</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sesena</contenido>
  </palabra>
  <palabra long="6">
    <contenido>susana</contenido>
  </palabra>
  <palabra long="6">
    <contenido>yusana</contenido>
  </palabra>
  <palabra long="7">
    <contenido>guasasa</contenido>
  </palabra>
  <palabra long="7">
    <contenido>guasaya</contenido>
  </palabra>
  <palabra long="7">
    <contenido>guayusa</contenido>
  </palabra>
  <palabra long="7">
    <contenido>guyanes</contenido>
    <palabreto/>
  </palabra>
  <palabra long="7">
    <contenido>yaguasa</contenido>
  </palabra>
  <palabra long="7">
    <contenido>yangues</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>guasanga</contenido>
  </palabra>
  <palabra long="8">
    <contenido>guayanes</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>guyanesa</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>sanguesa</contenido>
  </palabra>
  <palabra long="8">
    <contenido>sayagues</contenido>
  </palabra>
  <palabra long="8">
    <contenido>uyunense</contenido>
  </palabra>
  <palabra long="8">
    <contenido>yanguesa</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>guayanesa</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>sayaguesa</contenido>
  </palabra>
  <palabra long="10">
    <contenido>guayasense</contenido>
    <palabreto/>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/src/xml/Dias/Dia26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="26">
  <letraCentral>e</letraCentral>
  <letra>h</letra>
  <letra>i</letra>
  <letra>a</letra>
  <letra>l</letra>
  <letra>o</letra>
  <letra>d</letra>
  <letra>e</letra>
  
  <palabra long="3">
    <contenido>ahe</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ale</contenido>
  </palabra>
  <palabra long="3">
    <contenido>dea</contenido>
  </palabra>
  <palabra long="3">
    <contenido>del</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ele</contenido>
  </palabra>
  <palabra long="3">
    <contenido>led</contenido>
  </palabra>
  <palabra long="3">
    <contenido>leo</contenido>
  </palabra>
  <palabra long="3">
    <contenido>lle</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ole</contenido>
  </palabra>
  <palabra long="4">
    <contenido>aeda</contenido>
  </palabra>
  <palabra long="4">
    <contenido>aedo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>alea</contenido>
  </palabra>
  <palabra long="4">
    <contenido>aloe</contenido>
  </palabra>
  <palabra long="4">
    <contenido>deal</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dedo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dele</contenido>
  </palabra>
  <palabra long="4">
    <contenido>edad</contenido>
  </palabra>
  <palabra long="4">
    <contenido>edil</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ella</contenido>
  </palabra>
  <palabra long="4">
    <contenido>elle</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ello</contenido>
  </palabra>
  <palabra long="4">
    <contenido>hale</contenido>
  </palabra>
  <palabra long="4">
    <contenido>hiel</contenido>
  </palabra>
  <palabra long="4">
    <contenido>idea</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ideo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ileo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>leal</contenido>
  </palabra>
  <palabra long="4">
    <contenido>leda</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ledo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lela</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lelo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lied</contenido>
  </palabra>
  <palabra long="4">
    <contenido>oleo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>aldea</contenido>
  </palabra>
  <palabra long="5">
    <contenido>aleda</contenido>
  </palabra>
  <palabra long="5">
    <contenido>aleli</contenido>
  </palabra>
  <palabra long="5">
    <contenido>alelo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dalle</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dedal</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dedeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dedil</contenido>
  </palabra>
  <palabra long="5">
    <contenido>delia</contenido>
  </palabra>
  <palabra long="5">
    <contenido>delio</contenido>
  </palabra>
  <palabra long="5">
    <contenido>della</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dello</contenido>
  </palabra>
  <palabra long="5">
    <contenido>edila</contenido>
  </palabra>
  <palabra long="5">
    <contenido>eolia</contenido>
  </palabra>
  <palabra long="5">
    <contenido>eolio</contenido>
  </palabra>
  <palabra long="5">
    <contenido>helio</contenido>
  </palabra>
  <palabra long="5">
    <contenido>hielo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ideal</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ladeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>leida</contenido>
  </palabra>
  <palabra long="5">
    <contenido>leido</contenido>
  </palabra>
  <palabra long="5">
    <contenido>leila</contenido>
  </palabra>
  <palabra long="6">
    <contenido>alheli</contenido>
  </palabra>
  <palabra long="6">
    <contenido>dedada</contenido>
  </palabra>
  <palabra long="6">
    <contenido>dedalo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>deidad</contenido>
  </palabra>
  <palabra long="6">
    <contenido>delado</contenido>
  </palabra>
  <palabra long="6">
    <contenido>helada</contenido>
  </palabra>
  <palabra long="6">
    <contenido>helado</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lelili</contenido>
  </palabra>
  <palabra long="6">
    <contenido>oleada</contenido>
  </palabra>
  <palabra long="6">
    <contenido>oleado</contenido>
  </palabra>
  <palabra long="7">
    <contenido>adehala</contenido>
  </palabra>
  <palabra long="7">
    <contenido>alelada</contenido>
  </palabra>
  <palabra long="7">
    <contenido>alelado</contenido>
  </palabra>
  <palabra long="7">
    <contenido>dedillo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>hioidea</contenido>
  </palabra>
  <palabra long="7">
    <contenido>hioideo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ladeada</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ladeado</contenido>
  </palabra>
  <palabra long="7">
    <contenido>lealdad</contenido>
  </palabra>
  <palabra long="8">
    <contenido>aldehido</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>edilidad</contenido>
  </palabra>
  <palabra long="8">
    <contenido>haloidea</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>haloideo</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>hialoidea</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>hialoideo</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>idealidad</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia14.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="14">
  <letraCentral>o</letraCentral>
  <letra>h</letra>
  <letra>e</letra>
  <letra>t</letra>
  <letra>r</letra>
  <letra>o</letra>
  <letra>d</letra>
  <letra>x</letra>
  
  <palabra long="3">
    <contenido>ero</contenido>
  </palabra>
  <palabra long="3">
    <contenido>oro</contenido>
  </palabra>
  <palabra long="3">
    <contenido>oto</contenido>
  </palabra>
  <palabra long="3">
    <contenido>oxe</contenido>
  </palabra>
  <palabra long="3">
    <contenido>reo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dedo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dodo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dote</contenido>
  </palabra>
  <palabra long="4">
    <contenido>erro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>hoto</contenido>
  </palabra>
  <palabra long="4">
    <contenido>odre</contenido>
  </palabra>
  <palabra long="4">
    <contenido>oreo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>orto</contenido>
  </palabra>
  <palabra long="4">
    <contenido>otre</contenido>
  </palabra>
  <palabra long="4">
    <contenido>otro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>oxte</contenido>
  </palabra>
  <palabra long="4">
    <contenido>reto</contenido>
  </palabra>
  <palabra long="4">
    <contenido>rodo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>roer</contenido>
  </palabra>
  <palabra long="4">
    <contenido>roto</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tero</contenido>
  </palabra>
  <palabra long="4">
    <contenido>todo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>toro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tote</contenido>
  </palabra>
  <palabra long="4">
    <contenido>treo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>trox</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dedeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dotor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>error</contenido>
  </palabra>
  <palabra long="5">
    <contenido>exodo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>hedor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>heroe</contenido>
  </palabra>
  <palabra long="5">
    <contenido>heteo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>horre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>horro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>orero</contenido>
  </palabra>
  <palabra long="5">
    <contenido>otero</contenido>
  </palabra>
  <palabra long="5">
    <contenido>redor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>redox</contenido>
  </palabra>
  <palabra long="5">
    <contenido>redro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>retor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>retro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rodeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>roete</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rorro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rotor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tetro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>texto</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tordo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>toreo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>torre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>trote</contenido>
  </palabra>
  <palabra long="6">
    <contenido>dextro</contenido>
  </palabra>
  <palabra long="6">
    <contenido>etereo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>hetero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>horreo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>horror</contenido>
  </palabra>
  <palabra long="6">
    <contenido>odrero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>redero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>rodero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>rodete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>roedor</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tedero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>teredo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>terreo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>terror</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tetero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>todero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>torero</contenido>
  </palabra>
  <palabra long="6">
    <contenido>torete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tortor</contenido>
  </palabra>
  <palabra long="7">
    <contenido>derrote</contenido>
  </palabra>
  <palabra long="7">
    <contenido>exhorto</contenido>
  </palabra>
  <palabra long="7">
    <contenido>herrero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>horrero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>rededor</contenido>
  </palabra>
  <palabra long="7">
    <contenido>terrero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>torrero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>tortero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>tretero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>trotero</contenido>
  </palabra>
  <palabra long="8">
    <contenido>derredor</contenido>
  </palabra>
  <palabra long="8">
    <contenido>heredero</contenido>
  </palabra>
  <palabra long="8">
    <contenido>ortodoxo</contenido>
  </palabra>
  <palabra long="8">
    <contenido>ortoedro</contenido>
  </palabra>
  <palabra long="8">
    <contenido>totorero</contenido>
  </palabra>
  <palabra long="9">
    <contenido>derrotero</contenido>
  </palabra>
  <palabra long="9">
    <contenido>retortero</contenido>
  </palabra>
  <palabra long="10">
    <contenido>heterodoxo</contenido>
    <palabreto/>
  </palabra>
</dia>
