=== sadie27/TrabajoDistribuidos2025/bin/xml/DTD/PalabReto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dia (letraCentral, letra+, palabra+)>
<!ATTLIST dia
    id CDATA #REQUIRED
>
<!ELEMENT letraCentral (#PCDATA)>
<!ELEMENT letra (#PCDATA)>
<!ELEMENT palabra (contenido, palabreto?)>
<!ATTLIST palabra
    long CDATA #REQUIRED
>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT palabreto EMPTY>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="2">
  <letraCentral>s</letraCentral>
  <letra>d</letra>
  <letra>e</letra>
  <letra>m</letra>
  <letra>p</letra>
  <letra>l</letra>
  <letra>o</letra>
  
  <palabra long="3">
    <contenido>des</contenido>
  </palabra>
  <palabra long="5">
    <contenido>desde</contenido>
  </palabra>
  <palabra long="6">
    <contenido>desdel</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dese</contenido>
  </palabra>
  <palabra long="9">
    <contenido>desempleo</contenido>
    <palabreto/>
  </palabra>
  <palabra long="5">
    <contenido>deseo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>deseoso</contenido>
  </palabra>
  <palabra long="8">
    <contenido>desmolde</contenido>
  </palabra>
  <palabra long="9">
    <contenido>desmoldeo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>deso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>despeo</contenido>
  </palabra>
  <palabra long="8">
    <contenido>desplome</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>desplomo</contenido>
    <palabreto/>
  </palabra>
  <palabra long="6">
    <contenido>doloso</contenido>
  </palabra>
  <palabra long="3">
    <contenido>dos</contenido>
  </palabra>
  <palabra long="5">
    <contenido>dosel</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ellos</contenido>
  </palabra>
  <palabra long="5">
    <contenido>empos</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ese</contenido>
  </palabra>
  <palabra long="3">
    <contenido>eso</contenido>
  </palabra>
  <palabra long="4">
    <contenido>esos</contenido>
  </palabra>
  <palabra long="6">
    <contenido>espedo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>espeso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>esposo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>leseo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>leso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lodoso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lomoso</contenido>
  </palabra>
  <palabra long="3">
    <contenido>los</contenido>
  </palabra>
  <palabra long="3">
    <contenido>LSD</contenido>
  </palabra>
  <palabra long="6">
    <contenido>meloso</contenido>
  </palabra>
  <palabra long="3">
    <contenido>mes</contenido>
  </palabra>
  <palabra long="5">
    <contenido>mesmo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>modoso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>moloso</contenido>
  </palabra>
  <palabra long="5">
    <contenido>molso</contenido>
  </palabra>
  <palabra long="6">
    <contenido>oleoso</contenido>
  </palabra>
  <palabra long="4">
    <contenido>oseo</contenido>
  </palabra>
  <palabra long="3">
    <contenido>oso</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ososo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>peloso</contenido>
  </palabra>
  <palabra long="4">
    <contenido>peso</contenido>
  </palabra>
  <palabra long="5">
    <contenido>pesol</contenido>
  </palabra>
  <palabra long="7">
    <contenido>plomoso</contenido>
  </palabra>
  <palabra long="7">
    <contenido>pomposo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>popes</contenido>
  </palabra>
  <palabra long="3">
    <contenido>pos</contenido>
  </palabra>
  <palabra long="4">
    <contenido>pose</contenido>
  </palabra>
  <palabra long="6">
    <contenido>poseso</contenido>
  </palabra>
  <palabra long="5">
    <contenido>posmo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>poso</contenido>
  </palabra>
  <palabra long="7">
    <contenido>pospelo</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sed</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sede</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sedoso</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sel</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sello</contenido>
  </palabra>
  <palabra long="3">
    <contenido>seo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>sepe</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ses</contenido>
  </palabra>
  <palabra long="5">
    <contenido>seseo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sesmo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>seso</contenido>
  </palabra>
  <palabra long="3">
    <contenido>SMS</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sol</contenido>
  </palabra>
  <palabra long="6">
    <contenido>soldeo</contenido>
  </palabra>
  <palabra long="8">
    <contenido>soledoso</contenido>
  </palabra>
  <palabra long="5">
    <contenido>soleo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sollo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>solo</contenido>
  </palabra>
  <palabra long="6">
    <contenido>solomo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>somo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>sompopo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>soplo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>soso</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/bin/xml/Dias/Dia1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="1">
  <letraCentral>l</letraCentral>
  <letra>i</letra>
  <letra>l</letra>
  <letra>u</letra>
  <letra>s</letra>
  <letra>t</letra>
  <letra>r</letra>
  <letra>e</letra>
  
  <palabra long="3">
    <contenido>ele</contenido>
  </palabra>
  <palabra long="5">
    <contenido>elite</contenido>
  </palabra>
  <palabra long="4">
    <contenido>elle</contenido>
  </palabra>
  <palabra long="5">
    <contenido>eluir</contenido>
  </palabra>
  <palabra long="6">
    <contenido>esleer</contenido>
  </palabra>
  <palabra long="6">
    <contenido>esleir</contenido>
  </palabra>
  <palabra long="8">
    <contenido>estelles</contenido>
  </palabra>
  <palabra long="7">
    <contenido>esteril</contenido>
  </palabra>
  <palabra long="5">
    <contenido>estil</contenido>
  </palabra>
  <palabra long="8">
    <contenido>estilete</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ilustre</contenido>
    <palabreto/>
  </palabra>
  <palabra long="4">
    <contenido>iril</contenido>
  </palabra>
  <palabra long="7">
    <contenido>istulte</contenido>
  </palabra>
  <palabra long="4">
    <contenido>leer</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lelili</contenido>
  </palabra>
  <palabra long="9">
    <contenido>lessueste</contenido>
  </palabra>
  <palabra long="5">
    <contenido>leste</contenido>
  </palabra>
  <palabra long="8">
    <contenido>lesueste</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lilili</contenido>
  </palabra>
  <palabra long="3">
    <contenido>lis</contenido>
  </palabra>
  <palabra long="5">
    <contenido>lisis</contenido>
  </palabra>
  <palabra long="6">
    <contenido>listel</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lite</contenido>
  </palabra>
  <palabra long="5">
    <contenido>litis</contenido>
  </palabra>
  <palabra long="5">
    <contenido>litre</contenido>
  </palabra>
  <palabra long="3">
    <contenido>lle</contenido>
  </palabra>
  <palabra long="3">
    <contenido>lue</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lues</contenido>
  </palabra>
  <palabra long="4">
    <contenido>luir</contenido>
  </palabra>
  <palabra long="4">
    <contenido>luis</contenido>
  </palabra>
  <palabra long="4">
    <contenido>lulu</contenido>
  </palabra>
  <palabra long="5">
    <contenido>lurte</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lustre</contenido>
  </palabra>
  <palabra long="6">
    <contenido>lutier</contenido>
  </palabra>
  <palabra long="4">
    <contenido>rele</contenido>
  </palabra>
  <palabra long="6">
    <contenido>releer</contenido>
  </palabra>
  <palabra long="5">
    <contenido>retel</contenido>
  </palabra>
  <palabra long="6">
    <contenido>retril</contenido>
  </palabra>
  <palabra long="8">
    <contenido>retuelle</contenido>
  </palabra>
  <palabra long="4">
    <contenido>riel</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ristrel</contenido>
  </palabra>
  <palabra long="4">
    <contenido>rule</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rusel</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rutel</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sel</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sesil</contenido>
  </palabra>
  <palabra long="6">
    <contenido>sestil</contenido>
  </palabra>
  <palabra long="3">
    <contenido>sil</contenido>
  </palabra>
  <palabra long="7">
    <contenido>sillete</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sirle</contenido>
  </palabra>
  <palabra long="5">
    <contenido>sutil</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tele</contenido>
  </palabra>
  <palabra long="6">
    <contenido>telele</contenido>
  </palabra>
  <palabra long="9">
    <contenido>teleserie</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tell</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tertil</contenido>
  </palabra>
  <palabra long="4">
    <contenido>teul</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tile</contenido>
  </palabra>
  <palabra long="5">
    <contenido>titil</contenido>
  </palabra>
  <palabra long="9">
    <contenido>titulitis</contenido>
  </palabra>
  <palabra long="5">
    <contenido>trile</contenido>
  </palabra>
  <palabra long="3">
    <contenido>tul</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tule</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tullir</contenido>
  </palabra>
  <palabra long="6">
    <contenido>turril</contenido>
  </palabra>
  <palabra long="7">
    <contenido>turules</contenido>
  </palabra>
  <palabra long="4">
    <contenido>util</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/src/xml/Dias/Dia28.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="28">
  <letraCentral>u</letraCentral>
  <letra>b</letra>
  <letra>o</letra>
  <letra>q</letra>
  <letra>u</letra>
  <letra>e</letra>
  <letra>r</letra>
  <letra>n</letra>
  
  <palabra long="3">
    <contenido>bou</contenido>
  </palabra>
  <palabra long="3">
    <contenido>bue</contenido>
  </palabra>
  <palabra long="3">
    <contenido>que</contenido>
  </palabra>
  <palabra long="3">
    <contenido>rue</contenido>
  </palabra>
  <palabra long="3">
    <contenido>run</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ube</contenido>
  </palabra>
  <palabra long="3">
    <contenido>uno</contenido>
  </palabra>
  <palabra long="3">
    <contenido>uro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>buen</contenido>
  </palabra>
  <palabra long="4">
    <contenido>buro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>euro</contenido>
  </palabra>
  <palabra long="4">
    <contenido>nube</contenido>
  </palabra>
  <palabra long="4">
    <contenido>obue</contenido>
  </palabra>
  <palabra long="4">
    <contenido>oque</contenido>
  </palabra>
  <palabra long="4">
    <contenido>queo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>rubo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>runo</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ubre</contenido>
  </palabra>
  <palabra long="4">
    <contenido>urbe</contenido>
  </palabra>
  <palabra long="5">
    <contenido>beque</contenido>
  </palabra>
  <palabra long="5">
    <contenido>boque</contenido>
  </palabra>
  <palabra long="5">
    <contenido>bruno</contenido>
  </palabra>
  <palabra long="5">
    <contenido>bubon</contenido>
  </palabra>
  <palabra long="5">
    <contenido>bueno</contenido>
  </palabra>
  <palabra long="5">
    <contenido>buque</contenido>
  </palabra>
  <palabra long="5">
    <contenido>bureo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>burro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>eubeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>noque</contenido>
  </palabra>
  <palabra long="5">
    <contenido>queer</contenido>
  </palabra>
  <palabra long="5">
    <contenido>quero</contenido>
  </palabra>
  <palabra long="5">
    <contenido>roque</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rubeo</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rubor</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rubro</contenido>
  </palabra>
  <palabra long="5">
    <contenido>rurru</contenido>
  </palabra>
  <palabra long="5">
    <contenido>urubu</contenido>
  </palabra>
  <palabra long="6">
    <contenido>boruro</contenido>
  </palabra>
  <palabra long="6">
    <contenido>breque</contenido>
  </palabra>
  <palabra long="6">
    <contenido>eburno</contenido>
  </palabra>
  <palabra long="6">
    <contenido>queque</contenido>
  </palabra>
  <palabra long="6">
    <contenido>querer</contenido>
  </palabra>
  <palabra long="6">
    <contenido>querub</contenido>
  </palabra>
  <palabra long="6">
    <contenido>runrun</contenido>
  </palabra>
  <palabra long="7">
    <contenido>bourbon</contenido>
  </palabra>
  <palabra long="7">
    <contenido>burrero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>eburneo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>enroque</contenido>
  </palabra>
  <palabra long="7">
    <contenido>neneque</contenido>
  </palabra>
  <palabra long="7">
    <contenido>noquero</contenido>
  </palabra>
  <palabra long="7">
    <contenido>obenque</contenido>
  </palabra>
  <palabra long="7">
    <contenido>quequeo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>querque</contenido>
  </palabra>
  <palabra long="7">
    <contenido>querube</contenido>
  </palabra>
  <palabra long="7">
    <contenido>renqueo</contenido>
  </palabra>
  <palabra long="7">
    <contenido>roquero</contenido>
  </palabra>
  <palabra long="8">
    <contenido>boqueron</contenido>
    <palabreto/>
  </palabra>
  <palabra long="8">
    <contenido>brequero</contenido>
  </palabra>
  <palabra long="8">
    <contenido>rebenque</contenido>
  </palabra>
  <palabra long="8">
    <contenido>runruneo</contenido>
  </palabra>
  <palabra long="12">
    <contenido>querrequerre</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/src/xml/Dias/Dia13.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="13">
  <letraCentral>e</letraCentral>
  <letra>f</letra>
  <letra>r</letra>
  <letra>e</letra>
  <letra>c</letra>
  <letra>u</letra>
  <letra>n</letra>
  <letra>t</letra>
  
  <palabra long="3">
    <contenido>ecu</contenido>
  </palabra>
  <palabra long="3">
    <contenido>efe</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ene</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ere</contenido>
  </palabra>
  <palabra long="3">
    <contenido>fer</contenido>
  </palabra>
  <palabra long="3">
    <contenido>nen</contenido>
  </palabra>
  <palabra long="3">
    <contenido>rue</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ten</contenido>
  </palabra>
  <palabra long="3">
    <contenido>ter</contenido>
  </palabra>
  <palabra long="3">
    <contenido>uce</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cent</contenido>
  </palabra>
  <palabra long="4">
    <contenido>cute</contenido>
  </palabra>
  <palabra long="4">
    <contenido>ente</contenido>
  </palabra>
  <palabra long="4">
    <contenido>erre</contenido>
  </palabra>
  <palabra long="4">
    <contenido>eter</contenido>
  </palabra>
  <palabra long="4">
    <contenido>fuer</contenido>
  </palabra>
  <palabra long="4">
    <contenido>fuet</contenido>
  </palabra>
  <palabra long="4">
    <contenido>nene</contenido>
  </palabra>
  <palabra long="4">
    <contenido>rene</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tete</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tren</contenido>
  </palabra>
  <palabra long="4">
    <contenido>true</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tute</contenido>
  </palabra>
  <palabra long="4">
    <contenido>urce</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cerne</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cetre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>creer</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cruce</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cuete</contenido>
  </palabra>
  <palabra long="5">
    <contenido>curre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cuter</contenido>
  </palabra>
  <palabra long="5">
    <contenido>cutre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>entre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ercer</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ferre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>feten</contenido>
  </palabra>
  <palabra long="5">
    <contenido>frete</contenido>
  </palabra>
  <palabra long="5">
    <contenido>fuete</contenido>
  </palabra>
  <palabra long="5">
    <contenido>futre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>recre</contenido>
  </palabra>
  <palabra long="5">
    <contenido>reten</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ruter</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tener</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tenue</contenido>
  </palabra>
  <palabra long="5">
    <contenido>terne</contenido>
  </palabra>
  <palabra long="5">
    <contenido>trece</contenido>
  </palabra>
  <palabra long="5">
    <contenido>trefe</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cenete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>centen</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cercen</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cerete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cerner</contenido>
  </palabra>
  <palabra long="6">
    <contenido>crecer</contenido>
  </palabra>
  <palabra long="6">
    <contenido>cutete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>fernet</contenido>
  </palabra>
  <palabra long="6">
    <contenido>frente</contenido>
  </palabra>
  <palabra long="6">
    <contenido>frunce</contenido>
  </palabra>
  <palabra long="6">
    <contenido>fuente</contenido>
  </palabra>
  <palabra long="6">
    <contenido>fuerte</contenido>
  </palabra>
  <palabra long="6">
    <contenido>funene</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tercer</contenido>
  </palabra>
  <palabra long="6">
    <contenido>terere</contenido>
  </palabra>
  <palabra long="6">
    <contenido>terete</contenido>
  </palabra>
  <palabra long="6">
    <contenido>trecen</contenido>
  </palabra>
  <palabra long="6">
    <contenido>trente</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tuerce</contenido>
  </palabra>
  <palabra long="6">
    <contenido>urente</contenido>
  </palabra>
  <palabra long="6">
    <contenido>ureter</contenido>
  </palabra>
  <palabra long="7">
    <contenido>cercene</contenido>
  </palabra>
  <palabra long="7">
    <contenido>entente</contenido>
  </palabra>
  <palabra long="7">
    <contenido>fenecer</contenido>
  </palabra>
  <palabra long="7">
    <contenido>ferrete</contenido>
  </palabra>
  <palabra long="7">
    <contenido>furente</contenido>
  </palabra>
  <palabra long="7">
    <contenido>retener</contenido>
  </palabra>
  <palabra long="7">
    <contenido>retrete</contenido>
  </palabra>
  <palabra long="7">
    <contenido>tetunte</contenido>
  </palabra>
  <palabra long="8">
    <contenido>cerecere</contenido>
  </palabra>
  <palabra long="8">
    <contenido>eferente</contenido>
  </palabra>
  <palabra long="8">
    <contenido>enfrente</contenido>
  </palabra>
  <palabra long="8">
    <contenido>frutecer</contenido>
  </palabra>
  <palabra long="8">
    <contenido>recrecer</contenido>
  </palabra>
  <palabra long="8">
    <contenido>renuente</contenido>
  </palabra>
  <palabra long="8">
    <contenido>terrecer</contenido>
  </palabra>
  <palabra long="8">
    <contenido>teruteru</contenido>
  </palabra>
  <palabra long="9">
    <contenido>enfurecer</contenido>
  </palabra>
  <palabra long="9">
    <contenido>frecuente</contenido>
    <palabreto/>
  </palabra>
  <palabra long="9">
    <contenido>referente</contenido>
  </palabra>
  <palabra long="10">
    <contenido>enternecer</contenido>
  </palabra>
  <palabra long="10">
    <contenido>entretener</contenido>
  </palabra>
  <palabra long="10">
    <contenido>recurrente</contenido>
  </palabra>
</dia>

=== sadie27/TrabajoDistribuidos2025/src/xml/Dias/Dia7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dia SYSTEM "../DTD/PalabReto.dtd" >
<dia id="7">
  <letraCentral>t</letraCentral>
  <letra>d</letra>
  <letra>i</letra>
  <letra>f</letra>
  <letra>u</letra>
  <letra>n</letra>
  <letra>t</letra>
  <letra>a</letra>
  
  <palabra long="3">
    <contenido>DDT</contenido>
  </palabra>
  <palabra long="3">
    <contenido>tan</contenido>
  </palabra>
  <palabra long="3">
    <contenido>tau</contenido>
  </palabra>
  <palabra long="3">
    <contenido>tia</contenido>
  </palabra>
  <palabra long="3">
    <contenido>TNT</contenido>
  </palabra>
  <palabra long="3">
    <contenido>tun</contenido>
  </palabra>
  <palabra long="3">
    <contenido>uta</contenido>
  </palabra>
  <palabra long="4">
    <contenido>afta</contenido>
  </palabra>
  <palabra long="4">
    <contenido>anta</contenido>
  </palabra>
  <palabra long="4">
    <contenido>anti</contenido>
  </palabra>
  <palabra long="4">
    <contenido>atan</contenido>
  </palabra>
  <palabra long="4">
    <contenido>atun</contenido>
  </palabra>
  <palabra long="4">
    <contenido>data</contenido>
  </palabra>
  <palabra long="4">
    <contenido>dita</contenido>
  </palabra>
  <palabra long="4">
    <contenido>fata</contenido>
  </palabra>
  <palabra long="4">
    <contenido>fiat</contenido>
  </palabra>
  <palabra long="4">
    <contenido>inti</contenido>
  </palabra>
  <palabra long="4">
    <contenido>nata</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tana</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tata</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tatu</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tifa</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tina</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tita</contenido>
  </palabra>
  <palabra long="4">
    <contenido>titi</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tuda</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tuit</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tuna</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tuta</contenido>
  </palabra>
  <palabra long="4">
    <contenido>tutu</contenido>
  </palabra>
  <palabra long="5">
    <contenido>anata</contenido>
  </palabra>
  <palabra long="5">
    <contenido>antia</contenido>
  </palabra>
  <palabra long="5">
    <contenido>atada</contenido>
  </palabra>
  <palabra long="5">
    <contenido>ataud</contenido>
  </palabra>
  <palabra long="5">
    <contenido>danta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>fatua</contenido>
  </palabra>
  <palabra long="5">
    <contenido>finta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nafta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>natia</contenido>
  </palabra>
  <palabra long="5">
    <contenido>nauta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tafia</contenido>
  </palabra>
  <palabra long="5">
    <contenido>taifa</contenido>
  </palabra>
  <palabra long="5">
    <contenido>taina</contenido>
  </palabra>
  <palabra long="5">
    <contenido>taita</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tanda</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tanta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tinta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>titan</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tuani</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tuina</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tunda</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tunta</contenido>
  </palabra>
  <palabra long="5">
    <contenido>tutia</contenido>
  </palabra>
  <palabra long="6">
    <contenido>adnata</contenido>
  </palabra>
  <palabra long="6">
    <contenido>antana</contenido>
  </palabra>
  <palabra long="6">
    <contenido>atutia</contenido>
  </palabra>
  <palabra long="6">
    <contenido>finita</contenido>
  </palabra>
  <palabra long="6">
    <contenido>fututa</contenido>
  </palabra>
  <palabra long="6">
    <contenido>innata</contenido>
  </palabra>
  <palabra long="6">
    <contenido>nanita</contenido>
  </palabra>
  <palabra long="6">
    <contenido>nitida</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tantan</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tatita</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tinada</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tintin</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tuatua</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tunida</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tuntun</contenido>
  </palabra>
  <palabra long="6">
    <contenido>tununa</contenido>
  </palabra>
  <palabra long="6">
    <contenido>uniata</contenido>
  </palabra>
  <palabra long="6">
    <contenido>untada</contenido>
  </palabra>
  <palabra long="7">
    <contenido>afanita</contenido>
  </palabra>
  <palabra long="7">
    <contenido>anatada</contenido>
  </palabra>
  <palabra long="7">
    <contenido>atufada</contenido>
  </palabra>
  <palabra long="7">
    <contenido>difunta</contenido>
    <palabreto/>
  </palabra>
  <palabra long="7">
    <contenido>ditaina</contenido>
  </palabra>
  <palabra long="7">
    <contenido>finitud</contenido>
  </palabra>
  <palabra long="7">
    <contenido>infanta</contenido>
  </palabra>
  <palabra long="7">
    <contenido>infinta</contenido>
  </palabra>
  <palabra long="7">
    <contenido>tunanta</contenido>
  </palabra>
  <palabra long="8">
    <contenido>ataudada</contenido>
  </palabra>
  <palabra long="8">
    <contenido>fatuidad</contenido>
  </palabra>
  <palabra long="8">
    <contenido>inaudita</contenido>
  </palabra>
  <palabra long="8">
    <contenido>infinita</contenido>
  </palabra>
  <palabra long="8">
    <contenido>intifada</contenido>
  </palabra>
  <palabra long="9">
    <contenido>infantina</contenido>
  </palabra>
  <palabra long="9">
    <contenido>infinitud</contenido>
  </palabra>
  <palabra long="9">
    <contenido>tunantada</contenido>
  </palabra>
</dia>
